package jamulus

const (
	DEFAULT_PORT_NUMBER = 22124

	SYSTEM_SAMPLE_RATE_HZ = 48000

	FRAME_SIZE_FACTOR_PREFERRED = 1
	FRAME_SIZE_FACTOR_DEFAULT   = 2
	FRAME_SIZE_FACTOR_SAFE      = 4

	CELT_MINIMUM_NUM_BYTES = 10

	MIN_NET_BUF_SIZE_NUM_BL        = 1
	MAX_NET_BUF_SIZE_NUM_BL        = 20
	AUTO_NET_BUF_SIZE_FOR_PROTOCOL = MAX_NET_BUF_SIZE_NUM_BL + 1

	DEF_NET_BUF_SIZE_NUM_BL = 10

	AUD_MIX_FADER_MAX = 100
	AUD_MIX_PAN_MAX   = 100

	MAX_NUM_FADER_GROUPS = 4

	MAX_NUMBER_SOUND_CARDS = 129

	MAX_NUM_IN_OUT_CHANNELS = 64

	LOW_BOUND_SIG_METER   = -50.0
	UPPER_BOUND_SIG_METER = 0.0

	MAX_NUM_CHANNELS = 150

	DEFAULT_USED_NUM_CHANNELS = 10

	CHANNEL_LEVEL_UPDATE_INTERVAL = 200
)
